"use client";
import AutoGeneratedChannel from "@/components/videoUpload/autoGeneratedChannel";
import UploadForm from "@/components/videoUpload/upload";
import { useChannels } from "@/context/ChannelContext";
import React, { Suspense } from "react";
const page = () => {
	const { channels, selectedChannel } = useChannels();
	const currentChannel = selectedChannel !== null ? channels?.find(c => c._id === selectedChannel) : null;
	if (selectedChannel === null) return <div>Loading...</div>
	if (currentChannel?.auto_generated === true) return <AutoGeneratedChannel />
	return (
		<Suspense fallback={<div>Loading upload form...</div>}>
			<UploadForm />
		</Suspense>
	);
};

export default page;
