import type { Metadata } from "next";
import { Geist, Geist_Mono, Cascadia_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthProvider";
import { headers } from "next/headers";
import getUserInfo from "@/data/getUserInfo";
// import Header from "@/components/large/header";
import { NotificationContextProvider } from "@/context/NotificationProvider";
import getNotifications from "@/data/getNotifications";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const cascadiaMono = Cascadia_Mono({
	variable: "--font-cascadia-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Vid Platform",
	description: "Generated by create next app",
};

const getUser = async () => {
	const headerlist = await headers();
	const headerValue = headerlist.get("x-user-name");
	if (!headerValue) {
		return null;
	}
	const username = headerValue;
	const user = await getUserInfo(username);

	return user;
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const user = await getUser();
	let notifications = [];
	if(user){
		notifications = await getNotifications(user?.username || "");
	}
	const theme = user?.settings.theme;
	const themeClass = theme == "light" ? "light" : "dark";
	return (
		<html lang="en" className={themeClass}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${cascadiaMono.variable} antialiased`}
			>
				{user !== null ? (
					<AuthContextProvider initialValue={user}>
						<NotificationContextProvider initialValue={notifications}>
						{/* <Header /> */}
						{children}
						</NotificationContextProvider>
					</AuthContextProvider>
				) : (
					children
				)}
			</body>
		</html>
	);
}
