import type { Metadata } from "next";
import Header from "@/components/large/header";

export const metadata: Metadata = {
	title: "Vid Platform",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<Header />
			{children}
		</>
	);
}
